/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DealStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const ExpenseCategory = IDL.Variant({
  'salary' : IDL.Null,
  'other' : IDL.Text,
  'fuel' : IDL.Null,
  'toll' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const PartyType = IDL.Variant({
  'shipper' : IDL.Null,
  'both' : IDL.Null,
  'receiver' : IDL.Null,
});
export const TripStatus = IDL.Variant({
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'truck' : IDL.Null,
  'other' : IDL.Text,
  'trailer' : IDL.Null,
  'container' : IDL.Null,
});
export const VehicleStatus = IDL.Variant({
  'active' : IDL.Null,
  'idle' : IDL.Null,
  'maintenance' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MonthSummary = IDL.Record({
  'month' : IDL.Nat,
  'expenses' : IDL.Nat,
  'year' : IDL.Nat,
  'income' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'pendingDealsCount' : IDL.Nat,
  'monthlySummary' : IDL.Vec(MonthSummary),
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'activeTripsCount' : IDL.Nat,
});
export const Time = IDL.Int;
export const Deal = IDL.Record({
  'weight' : IDL.Nat,
  'status' : DealStatus,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'toCity' : IDL.Text,
  'fromCity' : IDL.Text,
  'loadDescription' : IDL.Text,
  'freightAmount' : IDL.Nat,
  'brokerCommission' : IDL.Nat,
  'partyId' : IDL.Nat,
});
export const Expense = IDL.Record({
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
  'vehicleId' : IDL.Opt(IDL.Nat),
});
export const Party = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'partyType' : PartyType,
  'phone' : IDL.Text,
});
export const Trip = IDL.Record({
  'status' : TripStatus,
  'expenses' : IDL.Nat,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'toCity' : IDL.Text,
  'fromCity' : IDL.Text,
  'freightAmount' : IDL.Nat,
  'driverName' : IDL.Text,
  'vehicleId' : IDL.Nat,
});
export const Vehicle = IDL.Record({
  'status' : VehicleStatus,
  'model' : IDL.Text,
  'vehicleType' : VehicleType,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        DealStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'addExpense' : IDL.Func(
      [ExpenseCategory, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'addParty' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, PartyType],
      [IDL.Nat],
      [],
    ),
  'addTrip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, TripStatus],
      [IDL.Nat],
      [],
    ),
  'addVehicle' : IDL.Func(
      [IDL.Text, IDL.Text, VehicleType, VehicleStatus],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDeals' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Deal))], ['query']),
  'listExpenses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Expense))],
      ['query'],
    ),
  'listParties' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Party))], ['query']),
  'listTrips' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Trip))], ['query']),
  'listVehicles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Vehicle))],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDeal' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        DealStatus,
      ],
      [],
      [],
    ),
  'updateParty' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PartyType],
      [],
      [],
    ),
  'updateTrip' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        TripStatus,
      ],
      [],
      [],
    ),
  'updateVehicle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, VehicleType, VehicleStatus],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DealStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const ExpenseCategory = IDL.Variant({
    'salary' : IDL.Null,
    'other' : IDL.Text,
    'fuel' : IDL.Null,
    'toll' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const PartyType = IDL.Variant({
    'shipper' : IDL.Null,
    'both' : IDL.Null,
    'receiver' : IDL.Null,
  });
  const TripStatus = IDL.Variant({
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const VehicleType = IDL.Variant({
    'truck' : IDL.Null,
    'other' : IDL.Text,
    'trailer' : IDL.Null,
    'container' : IDL.Null,
  });
  const VehicleStatus = IDL.Variant({
    'active' : IDL.Null,
    'idle' : IDL.Null,
    'maintenance' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MonthSummary = IDL.Record({
    'month' : IDL.Nat,
    'expenses' : IDL.Nat,
    'year' : IDL.Nat,
    'income' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'pendingDealsCount' : IDL.Nat,
    'monthlySummary' : IDL.Vec(MonthSummary),
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'activeTripsCount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Deal = IDL.Record({
    'weight' : IDL.Nat,
    'status' : DealStatus,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'toCity' : IDL.Text,
    'fromCity' : IDL.Text,
    'loadDescription' : IDL.Text,
    'freightAmount' : IDL.Nat,
    'brokerCommission' : IDL.Nat,
    'partyId' : IDL.Nat,
  });
  const Expense = IDL.Record({
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
    'vehicleId' : IDL.Opt(IDL.Nat),
  });
  const Party = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'partyType' : PartyType,
    'phone' : IDL.Text,
  });
  const Trip = IDL.Record({
    'status' : TripStatus,
    'expenses' : IDL.Nat,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'toCity' : IDL.Text,
    'fromCity' : IDL.Text,
    'freightAmount' : IDL.Nat,
    'driverName' : IDL.Text,
    'vehicleId' : IDL.Nat,
  });
  const Vehicle = IDL.Record({
    'status' : VehicleStatus,
    'model' : IDL.Text,
    'vehicleType' : VehicleType,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          DealStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'addExpense' : IDL.Func(
        [ExpenseCategory, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'addParty' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, PartyType],
        [IDL.Nat],
        [],
      ),
    'addTrip' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, TripStatus],
        [IDL.Nat],
        [],
      ),
    'addVehicle' : IDL.Func(
        [IDL.Text, IDL.Text, VehicleType, VehicleStatus],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDeals' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Deal))], ['query']),
    'listExpenses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Expense))],
        ['query'],
      ),
    'listParties' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Party))],
        ['query'],
      ),
    'listTrips' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, Trip))], ['query']),
    'listVehicles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Vehicle))],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDeal' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          DealStatus,
        ],
        [],
        [],
      ),
    'updateParty' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, PartyType],
        [],
        [],
      ),
    'updateTrip' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          TripStatus,
        ],
        [],
        [],
      ),
    'updateVehicle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, VehicleType, VehicleStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };