/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'pendingDealsCount' : bigint,
  'monthlySummary' : Array<MonthSummary>,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'activeTripsCount' : bigint,
}
export interface Deal {
  'weight' : bigint,
  'status' : DealStatus,
  'createdAt' : Time,
  'createdBy' : Principal,
  'toCity' : string,
  'fromCity' : string,
  'loadDescription' : string,
  'freightAmount' : bigint,
  'brokerCommission' : bigint,
  'partyId' : bigint,
}
export type DealStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export interface Expense {
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'category' : ExpenseCategory,
  'amount' : bigint,
  'vehicleId' : [] | [bigint],
}
export type ExpenseCategory = { 'salary' : null } |
  { 'other' : string } |
  { 'fuel' : null } |
  { 'toll' : null } |
  { 'maintenance' : null };
export interface MonthSummary {
  'month' : bigint,
  'expenses' : bigint,
  'year' : bigint,
  'income' : bigint,
}
export interface Party {
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'partyType' : PartyType,
  'phone' : string,
}
export type PartyType = { 'shipper' : null } |
  { 'both' : null } |
  { 'receiver' : null };
export type Time = bigint;
export interface Trip {
  'status' : TripStatus,
  'expenses' : bigint,
  'createdAt' : Time,
  'createdBy' : Principal,
  'toCity' : string,
  'fromCity' : string,
  'freightAmount' : bigint,
  'driverName' : string,
  'vehicleId' : bigint,
}
export type TripStatus = { 'completed' : null } |
  { 'ongoing' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'status' : VehicleStatus,
  'model' : string,
  'vehicleType' : VehicleType,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export type VehicleStatus = { 'active' : null } |
  { 'idle' : null } |
  { 'maintenance' : null };
export type VehicleType = { 'truck' : null } |
  { 'other' : string } |
  { 'trailer' : null } |
  { 'container' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeal' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, bigint, DealStatus],
    bigint
  >,
  'addExpense' : ActorMethod<
    [ExpenseCategory, bigint, string, [] | [bigint]],
    bigint
  >,
  'addParty' : ActorMethod<[string, string, string, PartyType], bigint>,
  'addTrip' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, TripStatus],
    bigint
  >,
  'addVehicle' : ActorMethod<
    [string, string, VehicleType, VehicleStatus],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDeals' : ActorMethod<[], Array<[bigint, Deal]>>,
  'listExpenses' : ActorMethod<[], Array<[bigint, Expense]>>,
  'listParties' : ActorMethod<[], Array<[bigint, Party]>>,
  'listTrips' : ActorMethod<[], Array<[bigint, Trip]>>,
  'listVehicles' : ActorMethod<[], Array<[bigint, Vehicle]>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDeal' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      DealStatus,
    ],
    undefined
  >,
  'updateParty' : ActorMethod<
    [bigint, string, string, string, PartyType],
    undefined
  >,
  'updateTrip' : ActorMethod<
    [bigint, bigint, string, string, string, bigint, bigint, TripStatus],
    undefined
  >,
  'updateVehicle' : ActorMethod<
    [bigint, string, string, VehicleType, VehicleStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];