/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthSummary {
    month: bigint;
    expenses: bigint;
    year: bigint;
    income: bigint;
}
export interface Trip {
    status: TripStatus;
    expenses: bigint;
    createdAt: Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    freightAmount: bigint;
    driverName: string;
    vehicleId: bigint;
}
export type Time = bigint;
export type ExpenseCategory = {
    __kind__: "salary";
    salary: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "fuel";
    fuel: null;
} | {
    __kind__: "toll";
    toll: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
};
export interface Expense {
    createdAt: Time;
    createdBy: Principal;
    description: string;
    category: ExpenseCategory;
    amount: bigint;
    vehicleId?: bigint;
}
export interface Vehicle {
    status: VehicleStatus;
    model: string;
    vehicleType: VehicleType;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
}
export interface DashboardStats {
    pendingDealsCount: bigint;
    monthlySummary: Array<MonthSummary>;
    totalIncome: bigint;
    totalExpenses: bigint;
    activeTripsCount: bigint;
}
export type VehicleType = {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "trailer";
    trailer: null;
} | {
    __kind__: "container";
    container: null;
};
export interface Party {
    city: string;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    partyType: PartyType;
    phone: string;
}
export interface Deal {
    weight: bigint;
    status: DealStatus;
    createdAt: Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    loadDescription: string;
    freightAmount: bigint;
    brokerCommission: bigint;
    partyId: bigint;
}
export interface UserProfile {
    name: string;
}
export enum DealStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed"
}
export enum PartyType {
    shipper = "shipper",
    both = "both",
    receiver = "receiver"
}
export enum TripStatus {
    completed = "completed",
    ongoing = "ongoing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleStatus {
    active = "active",
    idle = "idle",
    maintenance = "maintenance"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDeal(partyId: bigint, fromCity: string, toCity: string, loadDescription: string, weight: bigint, freightAmount: bigint, brokerCommission: bigint, status: DealStatus): Promise<bigint>;
    addExpense(category: ExpenseCategory, amount: bigint, description: string, vehicleId: bigint | null): Promise<bigint>;
    addParty(name: string, phone: string, city: string, partyType: PartyType): Promise<bigint>;
    addTrip(vehicleId: bigint, driverName: string, fromCity: string, toCity: string, freightAmount: bigint, expenses: bigint, status: TripStatus): Promise<bigint>;
    addVehicle(vehicleNumber: string, model: string, vehicleType: VehicleType, status: VehicleStatus): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listDeals(): Promise<Array<[bigint, Deal]>>;
    listExpenses(): Promise<Array<[bigint, Expense]>>;
    listParties(): Promise<Array<[bigint, Party]>>;
    listTrips(): Promise<Array<[bigint, Trip]>>;
    listVehicles(): Promise<Array<[bigint, Vehicle]>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateDeal(id: bigint, partyId: bigint, fromCity: string, toCity: string, loadDescription: string, weight: bigint, freightAmount: bigint, brokerCommission: bigint, status: DealStatus): Promise<void>;
    updateParty(id: bigint, name: string, phone: string, city: string, partyType: PartyType): Promise<void>;
    updateTrip(id: bigint, vehicleId: bigint, driverName: string, fromCity: string, toCity: string, freightAmount: bigint, expenses: bigint, status: TripStatus): Promise<void>;
    updateVehicle(id: bigint, vehicleNumber: string, model: string, vehicleType: VehicleType, status: VehicleStatus): Promise<void>;
}
import type { Deal as _Deal, DealStatus as _DealStatus, Expense as _Expense, ExpenseCategory as _ExpenseCategory, Party as _Party, PartyType as _PartyType, Time as _Time, Trip as _Trip, TripStatus as _TripStatus, UserProfile as _UserProfile, UserRole as _UserRole, Vehicle as _Vehicle, VehicleStatus as _VehicleStatus, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDeal(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: DealStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async addExpense(arg0: ExpenseCategory, arg1: bigint, arg2: string, arg3: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_ExpenseCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_ExpenseCategory_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addParty(arg0: string, arg1: string, arg2: string, arg3: PartyType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addParty(arg0, arg1, arg2, to_candid_PartyType_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParty(arg0, arg1, arg2, to_candid_PartyType_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addTrip(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: TripStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrip(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TripStatus_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrip(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TripStatus_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addVehicle(arg0: string, arg1: string, arg2: VehicleType, arg3: VehicleStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVehicle(arg0, arg1, to_candid_VehicleType_n10(this._uploadFile, this._downloadFile, arg2), to_candid_VehicleStatus_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVehicle(arg0, arg1, to_candid_VehicleType_n10(this._uploadFile, this._downloadFile, arg2), to_candid_VehicleStatus_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDeals(): Promise<Array<[bigint, Deal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeals();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeals();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExpenses(): Promise<Array<[bigint, Expense]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listParties(): Promise<Array<[bigint, Party]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParties();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParties();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrips(): Promise<Array<[bigint, Trip]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrips();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrips();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVehicles(): Promise<Array<[bigint, Vehicle]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVehicles();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVehicles();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateDeal(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: DealStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_DealStatus_n1(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updateParty(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: PartyType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0, arg1, arg2, arg3, to_candid_PartyType_n6(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0, arg1, arg2, arg3, to_candid_PartyType_n6(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: TripStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_TripStatus_n8(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_TripStatus_n8(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateVehicle(arg0: bigint, arg1: string, arg2: string, arg3: VehicleType, arg4: VehicleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVehicle(arg0, arg1, arg2, to_candid_VehicleType_n10(this._uploadFile, this._downloadFile, arg3), to_candid_VehicleStatus_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVehicle(arg0, arg1, arg2, to_candid_VehicleType_n10(this._uploadFile, this._downloadFile, arg3), to_candid_VehicleStatus_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_DealStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStatus): DealStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_PartyType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartyType): PartyType {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Party_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Party): Party {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TripStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripStatus): TripStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleStatus): VehicleStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Vehicle_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vehicle): Vehicle {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    status: _DealStatus;
    createdAt: _Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    loadDescription: string;
    freightAmount: bigint;
    brokerCommission: bigint;
    partyId: bigint;
}): {
    weight: bigint;
    status: DealStatus;
    createdAt: Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    loadDescription: string;
    freightAmount: bigint;
    brokerCommission: bigint;
    partyId: bigint;
} {
    return {
        weight: value.weight,
        status: from_candid_DealStatus_n23(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        toCity: value.toCity,
        fromCity: value.fromCity,
        loadDescription: value.loadDescription,
        freightAmount: value.freightAmount,
        brokerCommission: value.brokerCommission,
        partyId: value.partyId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: _Time;
    createdBy: Principal;
    description: string;
    category: _ExpenseCategory;
    amount: bigint;
    vehicleId: [] | [bigint];
}): {
    createdAt: Time;
    createdBy: Principal;
    description: string;
    category: ExpenseCategory;
    amount: bigint;
    vehicleId?: bigint;
} {
    return {
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        category: from_candid_ExpenseCategory_n29(_uploadFile, _downloadFile, value.category),
        amount: value.amount,
        vehicleId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.vehicleId))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: string;
    name: string;
    createdAt: _Time;
    createdBy: Principal;
    partyType: _PartyType;
    phone: string;
}): {
    city: string;
    name: string;
    createdAt: Time;
    createdBy: Principal;
    partyType: PartyType;
    phone: string;
} {
    return {
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        partyType: from_candid_PartyType_n36(_uploadFile, _downloadFile, value.partyType),
        phone: value.phone
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TripStatus;
    expenses: bigint;
    createdAt: _Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    freightAmount: bigint;
    driverName: string;
    vehicleId: bigint;
}): {
    status: TripStatus;
    expenses: bigint;
    createdAt: Time;
    createdBy: Principal;
    toCity: string;
    fromCity: string;
    freightAmount: bigint;
    driverName: string;
    vehicleId: bigint;
} {
    return {
        status: from_candid_TripStatus_n42(_uploadFile, _downloadFile, value.status),
        expenses: value.expenses,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        toCity: value.toCity,
        fromCity: value.fromCity,
        freightAmount: value.freightAmount,
        driverName: value.driverName,
        vehicleId: value.vehicleId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _VehicleStatus;
    model: string;
    vehicleType: _VehicleType;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
}): {
    status: VehicleStatus;
    model: string;
    vehicleType: VehicleType;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
} {
    return {
        status: from_candid_VehicleStatus_n48(_uploadFile, _downloadFile, value.status),
        model: value.model,
        vehicleType: from_candid_VehicleType_n50(_uploadFile, _downloadFile, value.vehicleType),
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy
    };
}
function from_candid_tuple_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Deal]): [bigint, Deal] {
    return [
        value[0],
        from_candid_Deal_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Expense]): [bigint, Expense] {
    return [
        value[0],
        from_candid_Expense_n27(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Party]): [bigint, Party] {
    return [
        value[0],
        from_candid_Party_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Trip]): [bigint, Trip] {
    return [
        value[0],
        from_candid_Trip_n40(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Vehicle]): [bigint, Vehicle] {
    return [
        value[0],
        from_candid_Vehicle_n46(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
}): DealStatus {
    return "cancelled" in value ? DealStatus.cancelled : "pending" in value ? DealStatus.pending : "completed" in value ? DealStatus.completed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salary: null;
} | {
    other: string;
} | {
    fuel: null;
} | {
    toll: null;
} | {
    maintenance: null;
}): {
    __kind__: "salary";
    salary: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "fuel";
    fuel: null;
} | {
    __kind__: "toll";
    toll: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
} {
    return "salary" in value ? {
        __kind__: "salary",
        salary: value.salary
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "fuel" in value ? {
        __kind__: "fuel",
        fuel: value.fuel
    } : "toll" in value ? {
        __kind__: "toll",
        toll: value.toll
    } : "maintenance" in value ? {
        __kind__: "maintenance",
        maintenance: value.maintenance
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipper: null;
} | {
    both: null;
} | {
    receiver: null;
}): PartyType {
    return "shipper" in value ? PartyType.shipper : "both" in value ? PartyType.both : "receiver" in value ? PartyType.receiver : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    ongoing: null;
}): TripStatus {
    return "completed" in value ? TripStatus.completed : "ongoing" in value ? TripStatus.ongoing : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    idle: null;
} | {
    maintenance: null;
}): VehicleStatus {
    return "active" in value ? VehicleStatus.active : "idle" in value ? VehicleStatus.idle : "maintenance" in value ? VehicleStatus.maintenance : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    truck: null;
} | {
    other: string;
} | {
    trailer: null;
} | {
    container: null;
}): {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "trailer";
    trailer: null;
} | {
    __kind__: "container";
    container: null;
} {
    return "truck" in value ? {
        __kind__: "truck",
        truck: value.truck
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "trailer" in value ? {
        __kind__: "trailer",
        trailer: value.trailer
    } : "container" in value ? {
        __kind__: "container",
        container: value.container
    } : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Deal]>): Array<[bigint, Deal]> {
    return value.map((x)=>from_candid_tuple_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Expense]>): Array<[bigint, Expense]> {
    return value.map((x)=>from_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Party]>): Array<[bigint, Party]> {
    return value.map((x)=>from_candid_tuple_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Trip]>): Array<[bigint, Trip]> {
    return value.map((x)=>from_candid_tuple_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Vehicle]>): Array<[bigint, Vehicle]> {
    return value.map((x)=>from_candid_tuple_n45(_uploadFile, _downloadFile, x));
}
function to_candid_DealStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): _DealStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_PartyType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): _PartyType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_TripStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): _TripStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): _VehicleStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "truck";
    truck: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "trailer";
    trailer: null;
} | {
    __kind__: "container";
    container: null;
}): {
    truck: null;
} | {
    other: string;
} | {
    trailer: null;
} | {
    container: null;
} {
    return value.__kind__ === "truck" ? {
        truck: value.truck
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "trailer" ? {
        trailer: value.trailer
    } : value.__kind__ === "container" ? {
        container: value.container
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleStatus): {
    active: null;
} | {
    idle: null;
} | {
    maintenance: null;
} {
    return value == VehicleStatus.active ? {
        active: null
    } : value == VehicleStatus.idle ? {
        idle: null
    } : value == VehicleStatus.maintenance ? {
        maintenance: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} {
    return value == DealStatus.cancelled ? {
        cancelled: null
    } : value == DealStatus.pending ? {
        pending: null
    } : value == DealStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "salary";
    salary: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "fuel";
    fuel: null;
} | {
    __kind__: "toll";
    toll: null;
} | {
    __kind__: "maintenance";
    maintenance: null;
}): {
    salary: null;
} | {
    other: string;
} | {
    fuel: null;
} | {
    toll: null;
} | {
    maintenance: null;
} {
    return value.__kind__ === "salary" ? {
        salary: value.salary
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "fuel" ? {
        fuel: value.fuel
    } : value.__kind__ === "toll" ? {
        toll: value.toll
    } : value.__kind__ === "maintenance" ? {
        maintenance: value.maintenance
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): {
    shipper: null;
} | {
    both: null;
} | {
    receiver: null;
} {
    return value == PartyType.shipper ? {
        shipper: null
    } : value == PartyType.both ? {
        both: null
    } : value == PartyType.receiver ? {
        receiver: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripStatus): {
    completed: null;
} | {
    ongoing: null;
} {
    return value == TripStatus.completed ? {
        completed: null
    } : value == TripStatus.ongoing ? {
        ongoing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
